const CLEAR_CART = 'CLEAR_CART';
const REMOVE_ITEM = 'REMOVE_ITEM';
const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';
const LOADING = 'LOADING';
const DISPLAY = 'DISPLAY';

export { CLEAR_CART, REMOVE_ITEM, INCREASE, DECREASE, LOADING, DISPLAY };
