const CLEAR_CART = 'CLEAR_CART';
const REMOVE_ITEM = 'REMOVE_ITEM';
const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
const DECREASE = 'DECREASE';
const LOADING = 'LOADING';
const DISPLAY = 'DISPLAY';

export { CLEAR_CART, REMOVE_ITEM, INCREASE_AMOUNT, DECREASE, LOADING, DISPLAY };
