const CLEAR_CART = 'CLEAR_CART';
const REMOVE_ITEM = 'REMOVE_ITEM';
const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
const DECREASE_AMOUNT = 'DECREASE_AMOUNT';
const LOADING = 'LOADING';
const DISPLAY = 'DISPLAY';

export {
  CLEAR_CART,
  REMOVE_ITEM,
  INCREASE_AMOUNT,
  DECREASE_AMOUNT,
  LOADING,
  DISPLAY,
};
